export const OUTLETS = [
  {
    id: "OUT-001",
    name: "Clean Express - Andheri",
    vendorId: "VND-001",
    vendorName: "Clean Express",
    location: "Andheri West, Mumbai",
    manager: "Suresh Menon",
    phone: "+91 98765 12345",
    status: "Active",
    ordersProcessed: 1250,
    rating: 4.8,
  },
  {
    id: "OUT-002",
    name: "Clean Express - Juhu",
    vendorId: "VND-001",
    vendorName: "Clean Express",
    location: "Juhu Tara Road, Mumbai",
    manager: "Ramesh Gupta",
    phone: "+91 98765 67890",
    status: "Active",
    ordersProcessed: 980,
    rating: 4.7,
  },
  {
    id: "OUT-003",
    name: "Sparkle Wash - Bandra",
    vendorId: "VND-002",
    vendorName: "Sparkle Wash",
    location: "Hill Road, Bandra West",
    manager: "Anita Desai",
    phone: "+91 87654 11223",
    status: "Active",
    ordersProcessed: 850,
    rating: 4.6,
  },
  {
    id: "OUT-004",
    name: "Fresh Laundry HQ",
    vendorId: "VND-003",
    vendorName: "Fresh Laundry",
    location: "Hiranandani, Powai",
    manager: "Vikram Seth",
    phone: "+91 76543 33445",
    status: "Active",
    ordersProcessed: 1540,
    rating: 4.9,
  },
  {
    id: "OUT-005",
    name: "Fresh Laundry - Vikhroli",
    vendorId: "VND-003",
    vendorName: "Fresh Laundry",
    location: "LBS Marg, Vikhroli",
    manager: "Karan Johar",
    phone: "+91 76543 55667",
    status: "Maintenance",
    ordersProcessed: 320,
    rating: 4.5,
  },
  {
    id: "OUT-006",
    name: "Quick Clean Central",
    vendorId: "VND-004",
    vendorName: "Quick Clean",
    location: "JVPD Scheme, Juhu",
    manager: "Neha Gupta",
    phone: "+91 65432 99887",
    status: "Inactive",
    ordersProcessed: 56,
    rating: 3.2,
  },
];
